name:                halftau
version:             0.1.0.0
github:              "alexandercampbell/halftau"
license:             BSD3
author:              "Alexander Campbell"
maintainer:          "alexanderhcampbell@gmail.com"
copyright:           "2019 Alexander Campbell"

description:         Please see the README on GitHub at <https://github.com/alexandercampbell/halftau#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - text
  - array
  - containers

executables:
  halftau-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halftau

tests:
  halftau-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - halftau

